# Generated by Django 6.0.3 on 2026-03-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_position_unique_together_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
