RATIO_DEFINITIONS = {
    'revenue_cagr': {
        'full_name': 'Croissance annualisée du CA',
        'definition': 'Taux de croissance annuel composé du chiffre d\'affaires sur la période.',
        'formula_th': '(CA_final / CA_initial)^(1/n) - 1',
        'formula_an': '(Revenue_n / Revenue_0)^(1/années) - 1',
    },
    'net_income_cagr': {
        'full_name': 'Croissance annualisée du résultat net',
        'definition': 'Taux de croissance annuel composé du bénéfice net sur la période.',
        'formula_th': '(RN_final / RN_initial)^(1/n) - 1',
        'formula_an': '(NetIncome_n / NetIncome_0)^(1/années) - 1',
    },
    'eps_cagr': {
        'full_name': 'Croissance annualisée du BPA',
        'definition': 'Taux de croissance annuel composé du bénéfice par action.',
        'formula_th': '(BPA_final / BPA_initial)^(1/n) - 1',
        'formula_an': '(EPS_n / EPS_0)^(1/années) - 1',
    },
    'fcf_cagr': {
        'full_name': 'Croissance annualisée du Free Cash Flow',
        'definition': 'Taux de croissance annuel composé du flux de trésorerie disponible.',
        'formula_th': '(FCF_final / FCF_initial)^(1/n) - 1',
        'formula_an': '(FreeCashFlow_n / FreeCashFlow_0)^(1/années) - 1',
    },
    'roe': {
        'full_name': 'Return on Equity',
        'definition': 'Mesure la rentabilité générée sur les capitaux propres des actionnaires.',
        'formula_th': 'Résultat net / Capitaux propres',
        'formula_an': 'NetIncome / TotalStockholdersEquity',
    },
    'roic': {
        'full_name': 'Return on Invested Capital',
        'definition': 'Mesure l\'efficacité avec laquelle l\'entreprise utilise son capital investi.',
        'formula_th': 'NOPAT / Capital investi',
        'formula_an': '(OperatingIncome × 0.75) / (Equity + Debt - Cash)',
    },
    'roa': {
        'full_name': 'Return on Assets',
        'definition': 'Mesure la rentabilité générée par l\'ensemble des actifs.',
        'formula_th': 'Résultat net / Total Actif',
        'formula_an': 'NetIncome / TotalAssets',
    },
    'net_margin': {
        'full_name': 'Marge nette',
        'definition': 'Part du chiffre d\'affaires qui se transforme en bénéfice net.',
        'formula_th': 'Résultat net / Chiffre d\'affaires',
        'formula_an': 'NetIncome / Revenue',
    },
    'gross_margin': {
        'full_name': 'Marge brute',
        'definition': 'Part du CA restante après déduction du coût des ventes.',
        'formula_th': 'Bénéfice brut / Chiffre d\'affaires',
        'formula_an': 'GrossProfit / Revenue',
    },
    'fcf_margin': {
        'full_name': 'Marge Free Cash Flow',
        'definition': 'Part du CA convertie en flux de trésorerie disponible.',
        'formula_th': 'Free Cash Flow / Chiffre d\'affaires',
        'formula_an': 'FreeCashFlow / Revenue',
    },
    'per': {
        'full_name': 'Price Earnings Ratio',
        'definition': 'Nombre de fois que le marché paie le bénéfice annuel par action.',
        'formula_th': 'Prix / Bénéfice par action',
        'formula_an': 'Price / EPS_diluted',
    },
    'peg': {
        'full_name': 'Price/Earnings to Growth',
        'definition': 'PER ajusté par la croissance. Un PEG < 1 signale une action potentiellement sous-évaluée.',
        'formula_th': 'PER / Taux de croissance BPA (%)',
        'formula_an': 'PER / EPS_CAGR',
    },
    'pb': {
        'full_name': 'Price to Book',
        'definition': 'Compare la valeur de marché aux actifs nets comptables.',
        'formula_th': 'Capitalisation / Valeur comptable',
        'formula_an': 'MarketCap / TotalStockholdersEquity',
    },
    'ps': {
        'full_name': 'Price to Sales',
        'definition': 'Compare la capitalisation boursière au chiffre d\'affaires annuel.',
        'formula_th': 'Capitalisation / Chiffre d\'affaires',
        'formula_an': 'MarketCap / Revenue',
    },
    'pcf': {
        'full_name': 'Price to Free Cash Flow',
        'definition': 'Compare la capitalisation au FCF, moins sensible aux manipulations comptables.',
        'formula_th': 'Capitalisation / Free Cash Flow',
        'formula_an': 'MarketCap / FreeCashFlow',
    },
    'ev_ebitda': {
        'full_name': 'Enterprise Value / EBITDA',
        'definition': 'Multiple de valorisation neutre à la structure de capital.',
        'formula_th': 'Valeur d\'entreprise / EBITDA',
        'formula_an': '(MarketCap + Debt - Cash) / EBITDA',
    },
    'ev_revenue': {
        'full_name': 'Enterprise Value / Revenue',
        'definition': 'Multiple de valorisation par rapport au CA. Utile pour les entreprises non profitables.',
        'formula_th': 'Valeur d\'entreprise / Chiffre d\'affaires',
        'formula_an': '(MarketCap + Debt - Cash) / Revenue',
    },
    'debt_to_equity': {
        'full_name': 'Ratio d\'endettement',
        'definition': 'Mesure le niveau d\'endettement par rapport aux fonds propres.',
        'formula_th': 'Dette totale / Fonds propres',
        'formula_an': 'TotalDebt / TotalStockholdersEquity',
    },
    'net_debt_ebitda': {
        'full_name': 'Levier financier net',
        'definition': 'Années d\'EBITDA pour rembourser la dette nette. < 2x est sain.',
        'formula_th': 'Dette nette / EBITDA',
        'formula_an': '(TotalDebt - Cash) / EBITDA',
    },
    'interest_coverage': {
        'full_name': 'Couverture des intérêts',
        'definition': 'Capacité à payer les charges d\'intérêts avec le résultat opérationnel.',
        'formula_th': 'Résultat opérationnel / Charges d\'intérêts',
        'formula_an': 'OperatingIncome / InterestExpense',
    },
    'current_ratio': {
        'full_name': 'Ratio de liquidité générale',
        'definition': 'Capacité à couvrir les dettes court terme avec les actifs courants. > 1.5 est sain.',
        'formula_th': 'Actifs courants / Passifs courants',
        'formula_an': 'TotalCurrentAssets / TotalCurrentLiabilities',
    },
    'quick_ratio': {
        'full_name': 'Ratio de liquidité immédiate',
        'definition': 'Liquidité immédiate excluant les stocks. Plus conservateur que le ratio courant.',
        'formula_th': '(Actifs courants - Stocks) / Passifs courants',
        'formula_an': '(CurrentAssets - Inventory) / CurrentLiabilities',
    },
}

VALUATION_DEFINITIONS = {
    'dcf': {
        'full_name': 'DCF Classique',
        'definition': 'Actualise les flux de trésorerie futurs projetés sur 10 ans. Méthode de référence en finance d\'entreprise.',
        'formula_th': 'Valeur = Σ FCF_t / (1+WACC)^t + Valeur terminale',
        'formula_an': 'FCF × (1+g1)^5 × (1+g2)^5 / (WACC - g_perp)',
        'reliability': 'Haute — mais très sensible aux hypothèses de croissance et au WACC.',
    },
    'buffett': {
        'full_name': 'Owner Earnings (Buffett)',
        'definition': 'Méthode de Warren Buffett basée sur les "Owner Earnings" — le cash réellement disponible pour les actionnaires.',
        'formula_th': 'Owner Earnings = RN + D&A - Capex maintenance',
        'formula_an': 'OE = NetIncome + Depreciation - (Capex × 0.7)',
        'reliability': 'Haute — très conservatrice, actualisée au taux du Trésor 30 ans.',
    },
    'graham': {
        'full_name': 'Graham Number',
        'definition': 'Formule de Benjamin Graham pour estimer la valeur intrinsèque d\'une action value. Très conservatrice.',
        'formula_th': '√(22.5 × BPA × Valeur comptable/action)',
        'formula_an': '√(22.5 × EPS_diluted × (Equity / Shares))',
        'reliability': 'Moyenne — adaptée aux entreprises matures avec actifs tangibles.',
    },
    'lynch': {
        'full_name': 'Peter Lynch Fair Value',
        'definition': 'Selon Peter Lynch, une action est fairly valued quand son PER = son taux de croissance (PEG = 1).',
        'formula_th': 'BPA × Taux de croissance (%)',
        'formula_an': 'EPS_diluted × FCF_CAGR',
        'reliability': 'Moyenne — simple mais ignore la structure de capital.',
    },
    'multiples': {
        'full_name': 'Multiples comparables',
        'definition': 'Valorise l\'entreprise en appliquant le PER moyen de son secteur à son bénéfice par action.',
        'formula_th': 'BPA × PER sectoriel moyen',
        'formula_an': 'EPS_diluted × PER_secteur',
        'reliability': 'Moyenne — dépend de la qualité des comparables sectoriels.',
    },
    'ddm': {
        'full_name': 'Dividend Discount Model',
        'definition': 'Valorise l\'action comme la somme des dividendes futurs actualisés. Ne s\'applique qu\'aux entreprises versant des dividendes.',
        'formula_th': 'P = D1 / (r - g)',
        'formula_an': 'DPS × (1+g) / (WACC - g_dividende)',
        'reliability': 'Haute pour les entreprises dividendes — N/A sinon.',
    },
}